[package]
name = "wasm-functions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arrow = "51.0.0"
wasm-udfs = { version = "0.1.0", path = "../wasm-udfs" }

[dev-dependencies]
wasm-bindgen-test = "0.3.43"
