[package]
name = "datafusion-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "45.0.0"
http-body = "1.0.1"
tower = "0.5.2"
tower-http = { version = "0.5.0", features = ["auth"] }
