install-deps:
    rustup target add wasm32-unknown-unknown

build-examples:
    cargo build --target=wasm32-unknown-unknown --release --manifest-path wasm-examples/Cargo.toml

copy-example-to-test: build-examples
    cp wasm-examples/target/wasm32-unknown-unknown/release/wasm_examples.wasm test-wasm/
